In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
type(iris)

sklearn.datasets.base.Bunch

In [3]:
print iris.data

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [4]:
print iris.feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print iris.target_names

['setosa' 'versicolor' 'virginica']


# Values of target_names
- setosa = 0
- versicolor = 1 
-  virginica = 2

In [6]:
print type(iris.data)
print type(iris.target)

<type 'numpy.ndarray'>
<type 'numpy.ndarray'>


In [10]:
print iris.data.shape
print iris.target.shape
# here L refers to long data type

(150L, 4L)
(150L,)


In [9]:
#feature
X = iris.data #matrix

y = iris.target #vector

## 4-step modelling pattern sckit learn
**step 1**: Import the class that you are going to use. 

In [11]:
from sklearn.neighbors import KNeighborsClassifier

**Step2:** "Instantiate" the "estimator"
- "Estimator" is a sckit-learn's term for model
- "Instantate" means "make an instance of"

In [19]:
knn = KNeighborsClassifier(n_neighbors=1)

- object "knn" - name doesn't matter
- free to specify parameters eg: n_neighbors=1 , ie look for 1 nearest neighbour
- unspecified paramters are set to default

In [20]:
# to find defaults, print the object like so
print knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


**Step 3:** Fit the model with data (aka "model training")
- model is learning the relationship with X & y
- occurs in-place

In [22]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

**Step 4:** Predict response for new observation
- new observations are called out of sample data
- uses info learned during training process

In [23]:
knn.predict([3,5,4,2])

C:\Program Files\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

- this Returns a numPy array
- can predict multiple observations at once

In [25]:
X_new= ([3,5,4,2],[5,4,3,2])
knn.predict(X_new)

array([2, 1])

# Using a different value of K

In [29]:
#instantiate the model
knn = KNeighborsClassifier(n_neighbors=5)
#let it learn (fit the model with data)
knn.fit(X,y)
#Predict - magic - Tada
knn.predict(X_new)

array([1, 1])

# Use a different model

In [32]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
#print logreg
#fit the data in the model
logreg.fit(X,y)
#predict the response 
logreg.predict(X_new)

array([2, 0])